#!/bin/bash

clear && clear
trap '' INT QUIT TSTP
IP=$(echo $SSH_CONNECTION | awk '{print $1, $2}')

allowed_commands=("ping" "tracepath" "plink" "ssh" "exit")
echo "Comandos Permitidos: ${allowed_commands[*]}"

while true; do
    read -e -p "Restricted: $ " -a cmd_parts
    while [[ -z ${cmd_parts[0]} ]]; do
        read -e -p "Restricted: $ " -a cmd_parts
    done
    
    first_word="${cmd_parts[0]}"
    cmd="${cmd_parts[*]}"
    echo "[ $(date +"%d/%m/%y %r")] Host: $IP  --  $cmd" >> /var/log/restricted_shell.log

    if [[ " ${allowed_commands[*]} " =~ " ${first_word} " ]]; then
        if [[ "${first_word}" == "exit" ]]; then
            exit 0
        else
            "${cmd_parts[@]}"
        fi
    else
        echo "Comando \"${cmd}\" no permitido. Comandos Permitidos: ${allowed_commands[*]}"
    fi
done
