version: '3.8'

services:
  security-toolkit:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: security-toolkit
    hostname: security-lab
    restart: unless-stopped
    ports:
      - "2222:22"     # SSH
      - "8080:8080"   # Para aplicaciones web
      - "4444:4444"   # Para Metasploit
      - "8000:8000"   # Para servidores web simples
    volumes:
      # Volúmenes persistentes
      - ./workspace:/home/security/workspace
      - ./reports:/home/security/reports
      - ./data:/home/security/data
      # Para acceder al socket de Docker del host (opcional)
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TZ=UTC        # Zona horaria, cambia según tu preferencia
      - DISPLAY=${DISPLAY:-:0.0}  # Para aplicaciones gráficas a través de X11 (opcional)
    cap_add:
      - NET_ADMIN     # Permitir administración de red
      - SYS_PTRACE    # Necesario para depuración
    # Para usar la red del host (útil para escaneo de red)
    # network_mode: host  # Descomenta si necesitas acceso directo a la red del host

  # Servicio opcional de base de datos (si lo necesitas)
  # database:
    # image: postgres:latest
    # container_name: security-db
    # restart: unless-stopped
    # environment:
      # - POSTGRES_PASSWORD=security123
      # - POSTGRES_USER=security
      # - POSTGRES_DB=securitydb
    # volumes:
      # - ./data/postgres:/var/lib/postgresql/data
    # ports:
      # - "5432:5432"

  # Opcional: Añadir un proxy de red como servicio
  # burp-proxy:
    # image: softwaresecurityproject/zap-stable
    # container_name: security-proxy
    # restart: unless-stopped
    # volumes:
      # - ./data/zap:/home/zap/.ZAP
    # ports:
      # - "8090:8080"    # Puerto web UI de ZAP
      # - "8091:8090"    # Puerto proxy de ZAP

volumes:
  workspace:
  reports:
  data:
